# -*- coding: utf-8 -*-
"""Task 3 - URL Shortner.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u_f7BCsHxpLFWn7MIctlUUbfKGpb0C2V
"""

import requests
def shorten_link(full_link, link_name):
    API_KEY = 'ba2a14042a43d0f69116f5b2f9e71a3c89db7'
    BASE_URL = 'https://cutt.ly/api/api.php'
    payload = {'key': API_KEY, 'short': full_link, 'name': link_name}
    request = requests.get(BASE_URL, params=payload)
    data = request.json()
    print('')

    try:
        title = data['url']['title']
        short_link = data['url']['shortLink']

        print('Title:', title)
        print('Link:', short_link)

    except:
        status = data['url']['status']
        print('Error Status:', status)
link = input('Enter a link: >>')
name = input('Give your link a name: >>')

shorten_link(link, name)